db = db.getSiblingDB('backup_harness_meta_store')
db.dropDatabase()
db = db.getSiblingDB('harness_meta_store')
db.copyDatabase("harness_meta_store", "backup_harness_meta_store")
db.dropDatabase()
db = db.getSiblingDB('harness_test_shared_users')
db.dropDatabase()
db = db.getSiblingDB('test_cb')
db.dropDatabase()
db = db.getSiblingDB('test_cb_2')
db.dropDatabase()
db = db.getSiblingDB('test_nh')
db.dropDatabase()
quit()
