#!/usr/bin/env bash

echo
echo "Usage: integration-test.sh run from harness/java-sdk. This runs several Engine specific tests."
echo "Each test saves a diff of expected and actual results that is printed at the end. There may be"
echo "some timing or other differences but as long as no significant query result differences exist"
echo "the test passes."
echo

#harness stop
#sleep 2
#harness start -f
#sleep 10

./contextual-bandit-integration-test.sh
./nav-hinting-integration-test.sh

echo
echo "========================================================================================================="
echo " Final Test Results, none is a passing test."
echo
echo "---------------------- Important differences: Contextual Bandit profile data ----------------------------"
diff example/test-profile-results.txt example/data/expected-test-profile-results.txt | grep Results
echo
echo "---------------------- Important differences: Contextual Bandit behavior data ----------------------------"
diff example/test-behavior-results.txt example/data/expected-test-behavior-results.txt | grep Results
echo
echo "---------------------- Important differences: Navigation Hinting queries ----------------------------"
diff example/nh-hinting-results.txt example/data/expected-nh-hinting-results.txt | grep Results
echo
